<a href="https://www.kaggle.com/code/regisvargas/introdu-o-ao-numpy-parte-3?scriptVersionId=216489590" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

<h1> Introdução ao Numpy - Parte 3</h1>

Este notebook pertence ao projeto [Ciência de dados e ML: fundamentos e aplicações](https://www.kaggle.com/code/regisvargas/ci-ncia-de-dados-e-ml-fundamentos-e-aplica-es).Vamos começar com a importação.

In [1]:
import numpy as np

Neste notebook, veremos como funcionam as operações matemáticas com arrays numpy. Vamos começar criando os vetores de exemplo *a* e *b*.

In [2]:
a = np.array([4, 8, 9])
b = np.array([8, 2, 3])

As operações aritméticas são aplicadas aos elementos correspondentes. Veja abaixo.

In [3]:
# [4+8, 8+2, 9+3]
print(a+b)

[12 10 12]


In [4]:
# [4-8, 8-2, 9-3]
print(a-b)

[-4  6  6]


In [5]:
# [4×8, 8×2, 9×3]
print(a*b)

[32 16 27]


In [6]:
#[4÷8, 8÷2, 9÷3]
print(a/b)

[0.5 4.  3. ]



Ao multiplicar um escalar por um array (e vice-versa), o resultado será um array com o mesmo formato (shape), onde todos os elementos do array original são multiplicados pelo escalar. Veja abaixo um exemplo para o array *a* e o escalar *1.5*

In [7]:
#[4×1.5, 8×1.5, 9×1.5]
print(1.5*a)

[ 6.  12.  13.5]


O mesmo vale para as outras operações aritméticas.

In [8]:
#[4÷2, 8÷2, 9÷2]
print(a/2)

[2.  4.  4.5]


In [9]:
#[4+3, 8+3, 9+3]
print(a+3)

[ 7 11 12]


In [10]:
#[4-5, 8-5, 9-5]
print(a-5)

[-1  3  4]


O primeiro índice de um array é o *zero. Assim: *a[0], a[1] e a[2]* valem, respectivamente, *4, 8, e 9*

In [11]:
print(a[0], a[1], a[2])

4 8 9


Vamos ver agora como obter apenas uma parte do array. A sintaxe para isso é *array[inicio:passo:fim]*. 

* Se não for passado o *inicio*, então, inicio será considerado zero;

* Se não for passado *passo*, então *passo* será considerado 1;

* Se não for passado *fim*, então *fim* será considerado *n-1* onde *n* é a quantidade de elementos no array. Lembre-se que o índice do array começa em zero.

Veja os exemplos abaixo.

In [12]:
ex = np.arange(2,8)
print(ex)

[2 3 4 5 6 7]


No exemplo abaixo, temos *inicio=0*, *passo=1* e *fim=1*.

Então, é retornado somente o primeiro elemento do array *ex*.

Isto ocorre porque o primeiro elemento a ser listado tem índice igual a *inicio* e o último elemento a ser listado tem índice igual a *fim-1*.

Assim, tanto o primeiro quanto o último elemento da lista são ex[0].

In [13]:
print(ex[:1])

[2]


Abaixo, temos *inicio=1*, *passo=1* e *fim=4*. Então, serão retornados os elementos de índices 1, 2 e 3.

In [14]:
print(ex[1:4])

[3 4 5]


Podemos retornar os dados do array de 2 em 2, por exemplo. Informando só o *passo*.

In [15]:
print(ex[::2])

[2 4 6]


Vamos ver agora, como esta estrutura funciona em um array de 2 dimensões. Veja abaixo que, neste caso, *ex_2d* é um "array de arrays". Isto é, o elemento no de índice zero é \[3,7,8]. Já o elemento de índice 1 é o \[4,5,8] e, por fim, o elemento de índice 2 é o \[2,4,7].

In [16]:
ex_2d = np.array([
    [3,7,8],
    [4,5,8],
    [2,4,7]
])

Então, o código abaixo, por exemplo, deve retornar os dois primeiros elementos de *ex_2d*.

In [17]:
print(ex_2d[0:2])

[[3 7 8]
 [4 5 8]]


Se quisermos, por exemplo, os dois primeiros números da primeira coluna, fazemos:

In [18]:
print(ex_2d[0:2,0])

[3 4]


Referência

[Mathematics for Machine Learning and Data Science Specialization](https://www.coursera.org/specializations/mathematics-for-machine-learning-and-data-science)

