# Resolução de um sistema linear a 3 incógnitas - Parte 3

Este notebook faz parte do projeto [Ciência de dados e ML: fundamentos e aplicações.](https://www.kaggle.com/code/regisvargas/ci-ncia-de-dados-e-ml-fundamentos-e-aplica-es)

Neste notebook, iremos abordar o seguinte sistema de equações a 3 incógnitas.

$$
\begin{cases}
6x  - y - z   &= 34 \\
5x + 6y + 5z &= 12 \\
11x + 5y + 4z &= 46
\end{cases}
$$

A matriz de coeficientes para este sistema é dada por:

In [47]:
import numpy as np

coeficientes = np.array([
    [6,-1,-1],
    [5, 6, 5],
    [11,5, 4]
], dtype = np.float64)

print(coeficientes)

[[ 6. -1. -1.]
 [ 5.  6.  5.]
 [11.  5.  4.]]


Vamos agora, calcular o determinante desta matriz.

In [48]:
print(np.linalg.det(coeficientes))

0.0


O determinante vale $0$, isto é, o determinante é igual a zero. [Como já vimos,](https://www.kaggle.com/code/regisvargas/sistema-linear-parte-5) quando o determinante dos coeficientes de um sistema linear é igual a zero, o sistema não tem solução, ou tem infinitas soluções.

Vamos resolver, passo a passo, este sistema. Vamos rever a matriz de coeficientes.

In [49]:
print(coeficientes)

[[ 6. -1. -1.]
 [ 5.  6.  5.]
 [11.  5.  4.]]


Podemos também, gerar a matriz de resultados. Veja abaixo.

In [50]:
resultados = np.array([
    [34],
    [12],
    [46]
], dtype = np.float32)
print(resultados)

[[34.]
 [12.]
 [46.]]


Utilizando a matriz `np.linalg.solve`, recebemos como resposta o erro de **matriz singular**. Justamente por causa do valor **zero** para o determinante da **matriz de coeficientes**.

In [51]:
print(np.linalg.solve(coeficientes, resultados))

LinAlgError: Singular matrix

Podemos, agora, através do empilhamento horizontal. Criar a matriz que representa o sistema.

In [52]:
sistema = np.hstack((coeficientes, resultados))
print(sistema)

[[ 6. -1. -1. 34.]
 [ 5.  6.  5. 12.]
 [11.  5.  4. 46.]]


Como sabemos, o primeiro elemento de um array Numpy tem indice $0$. Então, se quisermos retornar a segunda linha da matriz `sistema`, devemos utilizar `sistema[1]`. Veja abaixo.

In [53]:
print(sistema[1])

[ 5.  6.  5. 12.]


Podemos, agora, multiplicar a segunda linha da matriz por $\frac{6}{5}$.

In [54]:
print((6/5)*sistema[1])

[ 6.   7.2  6.  14.4]


E substrair, deste resultado, a primeira linha da matriz `sistema`.

In [55]:
print(((6/5)*sistema[1])-sistema[0])

[  0.    8.2   7.  -19.6]


Agora, vamos substituir a segunda linha da matriz `sistema` pela expressão acima.

In [56]:
sistema[1] = ((6/5)*sistema[1])-sistema[0]

A nova matriz `sistema` fica:

In [57]:
print(sistema)

[[  6.   -1.   -1.   34. ]
 [  0.    8.2   7.  -19.6]
 [ 11.    5.    4.   46. ]]


Multiplicamos a terceira linha da matriz `sistema` por $\frac{6}{11}$, ficamos com:

In [58]:
print((6/11)*sistema[2])

[ 6.          2.72727273  2.18181818 25.09090909]


Subtraindo deste resultado a primeira linha, temos:

In [59]:
print((6/11)*sistema[2]-sistema[0])

[ 0.          3.72727273  3.18181818 -8.90909091]


Substituido a terceira linha por este novo resultado, a nova matriz `sistema` fica dada por:

In [60]:
sistema[2] = (6/11)*sistema[2]-sistema[0]
print(sistema)

[[  6.          -1.          -1.          34.        ]
 [  0.           8.2          7.         -19.6       ]
 [  0.           3.72727273   3.18181818  -8.90909091]]


Multiplicando a terceira linha por $\frac{8.2}{3.72727273}$. Subtraindo deste resultado a segunda linha e, substituindo a terceira linha por este novo resultado temos a nova matriz sistema fica dada por:

In [61]:
sistema[2] = (8.2/3.72727273)*sistema[2]-sistema[1]
print(np.round(sistema,5))

[[  6.   -1.   -1.   34. ]
 [  0.    8.2   7.  -19.6]
 [  0.   -0.   -0.    0. ]]


Assim, o sistema inicial foi reescrito como:

$$
\begin{cases}
6x - y - z &= 34 \\
0x + 8.2y + 7z &= -19.6 \\
0x + 0y + 0z &= 0
\end{cases}
$$

A terceira linha deste sistema satizfaz a igualdade $0=0$ para qualquer valor de $x,$ $y$ e $z$. Então, esta terceira equação pode ser desconsiderada. Além disso, podemos desconsiderar o $0x$ da segunda equação, e o sistema pode ser reescrito como:

$$
\begin{cases}
6x - y - z &= 34 \\
8.2y + 7z &= -19.6 \\
\end{cases}
$$

Isolando $y$ na segunda equação temos:

$y = \frac{-19.6-7z}{8.2}$

Isolando $x$ na primeira equação temos:

$x = \frac{34+y+z}{6}$

Com estas equações, podemos montar o código que gera infinitas soluções para o sistema apresentado. Veja:

In [62]:
z = 0 #escolhemos z=0, mas você pode alterar pelo valor que você desejar

y = (-19.6-7*z)/8.2

x = (34+y+z)/6

print(f"({x},{y},{z}) é uma das solução para o sistema que possui infinitas soluções!")

(5.2682926829268295,-2.3902439024390247,0) é uma das solução para o sistema que possui infinitas soluções!


No código acima, escolhemos $z=0$, mas poderíamos ter escolhido qualquer outro valor para $z$. Para cada valor de $z$, podemos calcular $x$ e $y$ de forma que $(x,y,z)$ satisfaça o sistema fornecido inicialmente. Como podemos escolher infinitos valores para $z$, então existem infinitas soluções para o sistema fornecido.

Para concluir, vamos retomar o sistema fornecido inicialmente.

$$
\begin{cases}
6x  - y - z   &= 34 \\
5x + 6y + 5z &= 12 \\
11x + 5y + 4z &= 46
\end{cases}
$$

Pelo código abaixo, vemos que os valores $x$, $y$ e $z$ satisfazem as três equações acima.

In [63]:
print(6*x-y-z)
print(5*x+6*y+5*z)
print(11*x+5*y+4*z)

34.0
12.0
46.0


Referências

[Mathematics for Machine Learning and Data Science Specialization](https://www.coursera.org/specializations/mathematics-for-machine-learning-and-data-science)
