<a href="https://www.kaggle.com/code/regisvargas/sistema-linear-parte-3?scriptVersionId=218117842" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

<h1>Resolução de um sistema linear a 2 incógnitas - Parte 3</h1>

Este notebook faz parte do projeto [Ciência de dados e ML: fundamentos e aplicações.](https://www.kaggle.com/code/regisvargas/ci-ncia-de-dados-e-ml-fundamentos-e-aplica-es)

Neste notebook, desenvolveremos o código que implementa o método de eliminação no sistema de equações que estamos utilizando como exemplo.

Vamos retomar o sistema de equações que estamos abordando.

$$
\begin{cases}
-1x+1y=1\\
4x-2y=4
\end{cases}
$$

[Como vimos](https://www.kaggle.com/code/regisvargas/sistema-linear-parte-1), as matrizes de coeficientes e de resultados são:

In [1]:
import numpy as np

coeficientes = np.array([
    [-1,1],
    [4,-2]
])

resultados = np.array([
    [1],
    [4]
])

[Nos notebooks introdutórios sobre Numpy](https://www.kaggle.com/code/regisvargas/ci-ncia-de-dados-e-ml-fundamentos-e-aplica-es), vimos que podemos empilhar estas matrizes horizontalmente usando a função *np.hstack*. Utilizando esta função, podemos construir a matriz que representa o sistema como um todo. Veja abaixo.

In [2]:
sistema = np.hstack((coeficientes, resultados))
print(sistema)

[[-1  1  1]
 [ 4 -2  4]]


Vamos fazer a cópia da matriz *sistema*.

In [3]:
sistema_cp = sistema.copy()

Na [parte 2](https://www.kaggle.com/code/regisvargas/sistema-linear-parte-2) utilizamos o método de eliminação para resolver o sistema. Esse método consistia em multiplicar a primeira linha por $4$ e somar o resultado desta multiplicação a segunda linha.

Vamos implementar, passo a passo, em python, este raciocínio.

Como já vimos, o índice de um array inicia em zero. Então, a primeira linha da matriz *sistema_cp* é dada por *sistema_cp[0]*. Veja abaixo.

In [4]:
print(sistema_cp[0])

[-1  1  1]


Multiplicando esta linha por $4$, temos:

In [5]:
print(4*sistema_cp[0])

[-4  4  4]


E, somando este valor a segunda linha desta mesma matriz, temos:

In [6]:
print(4*sistema_cp[0]+sistema_cp[1])

[0 2 8]


Para representarmos a equação $0x+1y=4$ (que nos dá, na prática, a solução $y=4$). Podemos multiplicar toda a expressão anterior por $0.5$. Veja abaixo:

In [7]:
print(0.5*(4*sistema_cp[0]+sistema_cp[1]))

[0. 1. 4.]


Vamos agora, substituir a segunda linha da matriz *sistema_cp* pela linha calculada acima.

In [8]:
sistema_cp[1] = 0.5*(4*sistema_cp[0]+sistema_cp[1])
print(sistema_cp)

[[-1  1  1]
 [ 0  1  4]]


Podemos, agora, substituir a primeira linha por: primeira linha multiplicada por $-1$ mais a segunda linha. 

In [9]:
sistema_cp[0] = sistema_cp[0]*(-1)\
              + sistema_cp[1]

O que nos dá a seguinte matriz resultante:

In [10]:
print(sistema_cp)

[[1 0 3]
 [0 1 4]]


Esta matriz representa a solução do sistema, pois ela nos diz que $1x+0y=3$, o que equivale a $x=3.$ Além disso, ela também nos diz que $0x+1y=4$, o que equivale a $y=4$. 

[Como já vimos](https://www.kaggle.com/code/regisvargas/sistema-linear-parte-2), estas são, de fato as soluções do sistema de equações apresentado no início deste notebook.

Referências

[Mathematics for Machine Learning and Data Science Specialization](https://www.coursera.org/specializations/mathematics-for-machine-learning-and-data-science)