# Resolução de um sistema linear a 3 incógnitas - Parte 2

Este notebook faz parte do projeto [Ciência de dados e ML: fundamentos e aplicações.](https://www.kaggle.com/code/regisvargas/ci-ncia-de-dados-e-ml-fundamentos-e-aplica-es)

Neste notebook, iremos abordar o seguinte sistema de equações a 3 incógnitas.

$$
\begin{cases}
3x + y + z &= 15 \\
2x + 7y + 2z &= 42 \\
3x + y + z &= 23
\end{cases}
$$

A matriz de coeficientes para este sistema é dada por:

In [1]:
import numpy as np

coeficientes = np.array([
    [3,1,1],
    [2,7,2],
    [3,1,1]
], dtype = np.float64)

print(coeficientes)

[[3. 1. 1.]
 [2. 7. 2.]
 [3. 1. 1.]]


Vamos agora, calcular o determinante desta matriz.

In [2]:
print(np.linalg.det(coeficientes))

0.0


O determinante vale $0$, isto é, o determinante é igual a zero. [Como já vimos,](https://www.kaggle.com/code/regisvargas/sistema-linear-parte-5) quando o determinante dos coeficientes de um sistema linear é igual a zero, o sistema não tem solução, ou tem infinitas soluções.

Vamos resolver, passo a passo, este sistema. Vamos rever a matriz de coeficientes.

In [3]:
print(coeficientes)

[[3. 1. 1.]
 [2. 7. 2.]
 [3. 1. 1.]]


Podemos também, gerar a matriz de resultados. Veja abaixo.

In [4]:
resultados = np.array([
    [15],
    [42],
    [23]
], dtype = np.float64)
print(resultados)

[[15.]
 [42.]
 [23.]]


Utilizando a matriz `np.linalg.solve`, recebemos como resposta o erro de **matriz singular**. Justamente por causa do valor **zero** para o determinante da **matriz de coeficientes**.

In [5]:
print(np.linalg.solve(coeficientes, resultados))

LinAlgError: Singular matrix

Podemos, agora, através do empilhamento horizontal. Criar a matriz que representa o sistema.

In [ ]:
sistema = np.hstack((coeficientes, resultados))
print(sistema)

Como sabemos, o primeiro elemento de um array Numpy tem indice $0$. Então, se quisermos retornar a segunda linha da matriz `sistema`, devemos utilizar `sistema[1]`. Veja abaixo.

In [ ]:
print(sistema[1])

Podemos, agora, dividir a segunda linha da matriz por 2.

In [ ]:
print(sistema[1]/2)

E substrair, deste resultado, a primeira linha da matriz `sistema`.

In [ ]:
print((sistema[1]/2)-sistema[0])

Agora, vamos substituir a segunda linha da matriz `sistema` pela expressão acima.

In [ ]:
sistema[1] = (sistema[1]/2)-sistema[0]

A nova matriz `sistema` fica:

In [ ]:
print(sistema)

Multiplicando a terceira linha da matriz `sistema` por $-2$ ficamos com:

In [ ]:
print(-2*sistema[2])

Subtraindo, deste resultado, a primeira linha temos:

In [ ]:
print(-2*sistema[2]-sistema[0])

Substituindo a terceira linha por esta nova linha, temos:

In [ ]:
sistema[2] = -2*sistema[2]-sistema[0]

E a nova matriz `sistema` fica dada por:

In [ ]:
print(sistema)

Multiplicando a terceira linha da matriz `sistema` por $\frac{-3.5}{-13}$, temos:

In [ ]:
print((-3.5/-13)*sistema[2])

Subtraindo, deste resultado, a segunda linha, temos:

In [ ]:
print((-3.5/-13)*sistema[2]-sistema[1])

Fazendo a substituição, na matriz `sistema", da terceira linha pela linha acima, temos:

In [ ]:
sistema[2] = (-3.5/-13)*sistema[2]-sistema[1]

print(sistema)

Assim, o sistema inicial foi reescrito como:

$$
\begin{cases}
2x + 3y - z &= 5 \\
0x - 3.5y + 2z &= -2 \\
0x + 0y - 3.34615385z &= 2.80769231
\end{cases}
$$

Assim, o valor de $z$ é:

In [ ]:
z = 2.80769231/(-3.34615385)
print(z)

Tendo o valor de $z$, calculamos o valor de $y$, por:

In [ ]:
y = (-2-2*z)/(-3.5)
print(y)

Tendo o valor de $z$ e de $y$, calculamos $x$ por:

In [ ]:
x = (5+z-3*y)/2
print(x)

Referências

[Mathematics for Machine Learning and Data Science Specialization](https://www.coursera.org/specializations/mathematics-for-machine-learning-and-data-science)
