# Resolução de um sistema linear a 3 incógnitas - Parte 2

Este notebook faz parte do projeto [Ciência de dados e ML: fundamentos e aplicações.](https://www.kaggle.com/code/regisvargas/ci-ncia-de-dados-e-ml-fundamentos-e-aplica-es)

Neste notebook, iremos abordar o seguinte sistema de equações a 3 incógnitas.

$$
\begin{cases}
3x + y + z &= 15 \\
2x + 7y + 2z &= 42 \\
3x + y + z &= 23
\end{cases}
$$

A matriz de coeficientes para este sistema é dada por:

In [1]:
import numpy as np

coeficientes = np.array([
    [3,1,1],
    [2,7,2],
    [3,1,1]
], dtype = np.float64)

print(coeficientes)

[[3. 1. 1.]
 [2. 7. 2.]
 [3. 1. 1.]]


Vamos agora, calcular o determinante desta matriz.

In [2]:
print(np.linalg.det(coeficientes))

0.0


O determinante vale $0$, isto é, o determinante é igual a zero. [Como já vimos,](https://www.kaggle.com/code/regisvargas/sistema-linear-parte-5) quando o determinante dos coeficientes de um sistema linear é igual a zero, o sistema não tem solução, ou tem infinitas soluções.

Vamos resolver, passo a passo, este sistema. Vamos rever a matriz de coeficientes.

In [3]:
print(coeficientes)

[[3. 1. 1.]
 [2. 7. 2.]
 [3. 1. 1.]]


Podemos também, gerar a matriz de resultados. Veja abaixo.

In [4]:
resultados = np.array([
    [15],
    [42],
    [23]
], dtype = np.float64)
print(resultados)

[[15.]
 [42.]
 [23.]]


Utilizando a matriz `np.linalg.solve`, recebemos como resposta o erro de **matriz singular**. Justamente por causa do valor **zero** para o determinante da **matriz de coeficientes**.

In [5]:
print(np.linalg.solve(coeficientes, resultados))

LinAlgError: Singular matrix

Podemos, agora, através do empilhamento horizontal. Criar a matriz que representa o sistema.

In [6]:
sistema = np.hstack((coeficientes, resultados))
print(sistema)

[[ 3.  1.  1. 15.]
 [ 2.  7.  2. 42.]
 [ 3.  1.  1. 23.]]


Como sabemos, o primeiro elemento de um array Numpy tem indice $0$. Então, se quisermos retornar a segunda linha da matriz `sistema`, devemos utilizar `sistema[1]`. Veja abaixo.

In [7]:
print(sistema[1])

[ 2.  7.  2. 42.]


Podemos, agora, multiplicar a segunda linha da matriz por $1.5$.

In [8]:
print(1.5*sistema[1])

[ 3.  10.5  3.  63. ]


E substrair, deste resultado, a primeira linha da matriz `sistema`.

In [9]:
print((1.5*sistema[1])-sistema[0])

[ 0.   9.5  2.  48. ]


Agora, vamos substituir a segunda linha da matriz `sistema` pela expressão acima.

In [10]:
sistema[1] = (1.5*sistema[1])-sistema[0]

A nova matriz `sistema` fica:

In [11]:
print(sistema)

[[ 3.   1.   1.  15. ]
 [ 0.   9.5  2.  48. ]
 [ 3.   1.   1.  23. ]]


Subtraindo a primeira linha da terceira linha, na matriz `sistema`, ficamos com:

In [12]:
print(sistema[2]-sistema[0])

[0. 0. 0. 8.]


Substituindo a terceira linha por esta nova linha, temos:

In [13]:
sistema[2] = sistema[2]-sistema[0]

E a nova matriz `sistema` fica dada por:

In [14]:
print(sistema)

[[ 3.   1.   1.  15. ]
 [ 0.   9.5  2.  48. ]
 [ 0.   0.   0.   8. ]]


Assim, o sistema inicial foi reescrito como:

$$
\begin{cases}
3x + y + z &= 15 \\
0x + 9.5y + 2z &= 48 \\
0x + 0y + 0z &= 8
\end{cases}
$$

Não é necessário fazer mais nenhum cálculo. Uma vez que a última linha deste sistema gera uma igualdade falsa: $0=8$. O que equivale a dizer que o sistema não tem solução.

Referências

[Mathematics for Machine Learning and Data Science Specialization](https://www.coursera.org/specializations/mathematics-for-machine-learning-and-data-science)
